name: VEGA Universal APK Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant Gradle Permission
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Show All APK Files (Deep Scan)
        run: |
          echo "Scanning for APK files..."
          find . -type f -name "*.apk"

      - name: Upload All APK Files
        uses: actions/upload-artifact@v4
        with:
          name: VEGA-ALL-APK
          path: '**/*.apk'
